[package]
name = "ogit-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { "version" = "4.6.1", features = ["cargo", "derive"] }
crossterm = "0.29.0"
ratatui = "0.30.0"

# Clipboard
arboard = "3"

# Backend / data handling
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.127"


# Styling / color helpers
csscolorparser = "0.7.0"
pulldown-cmark = "0.12"

# Date/time utilities
chrono = "0.4"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
