[package]
name = "ogit"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["cargo", "derive"] }
config-file = "0.2.3"
human-panic = "2.0.1"
serde = { version = "1.0.208", features = ["derive"] }
